#!/usr/bin/env python3
"""Generate the LVGL font subset of Material Design Icons used by the dongle UI.

The dongle screen was specified with MDI icons, and LVGL cannot load an SVG
icon set at runtime, so the handful of glyphs the UI needs are baked into a
font at build time. Everything is regenerated from scratch here — the C files
under boards/shields/dongle_tft/ are output, not sources.

    python3 tools/gen_mdi_font.py

Needs network access (to fetch the pinned MDI webfont) and node, for
lv_font_conv, which is run through npx.

MDI codepoints live in plane 15 (U+F0000+), which would make every icon a
four-byte UTF-8 sequence. They are remapped into the basic-plane private use
area starting at U+E000 instead, so the strings in mdi_icons.h stay three
bytes and stay readable in a hex dump.
"""

import pathlib
import re
import subprocess
import sys
import tempfile
import urllib.request

MDI_VERSION = "7.4.47"
BASE = f"https://raw.githubusercontent.com/Templarian/MaterialDesign-Webfont/v{MDI_VERSION}"
TTF_URL = f"{BASE}/fonts/materialdesignicons-webfont.ttf"
SCSS_URL = f"{BASE}/scss/_variables.scss"

# First free codepoint of the basic-plane private use area.
PUA_BASE = 0xE000

# Icons the UI draws, in the order they get their private codepoints. Keep
# this list in sync with the usages in dongle_ui.c and keymap_legend.c.
ICONS = [
    # status row
    "usb",
    "bluetooth",
    "bluetooth-connect",
    "bluetooth-off",
    # modifiers, also used as key legends on Nav and Mouse
    "apple-keyboard-shift",
    "apple-keyboard-control",
    "apple-keyboard-option",
    "apple-keyboard-command",
    "apple-keyboard-caps",
    # navigation
    "arrow-up",
    "arrow-down",
    "arrow-left",
    "arrow-right",
    "arrow-collapse-left",
    "arrow-collapse-right",
    "chevron-double-up",
    "chevron-double-down",
    # editing
    "keyboard-return",
    "keyboard-tab",
    "keyboard-esc",
    "keyboard-space",
    "backspace-outline",
    "backspace-reverse-outline",
    # media
    "volume-off",
    "volume-medium",
    "volume-high",
    "skip-previous",
    "play-pause",
    "brightness-5",
    "brightness-7",
    "skip-next",
]

# One font per size: 12 px for the keymap, the status row and the modifiers,
# 10 px for the system monitor's up/down arrows, which sit in a montserrat_10
# row and would look heavy at 12.
SIZES = [12, 10]

OUT_DIR = pathlib.Path(__file__).resolve().parent.parent / "boards/shields/dongle_tft"


def macro_name(icon: str) -> str:
    return "MDI_" + icon.upper().replace("-", "_")


def fetch(url: str, dest: pathlib.Path) -> None:
    print(f"fetching {url}")
    with urllib.request.urlopen(url) as response:
        dest.write_bytes(response.read())


def codepoints(scss: str) -> dict:
    return {
        name: int(code, 16)
        for name, code in re.findall(r'^\s+"([a-z0-9-]+)":\s*([0-9A-F]+),', scss, re.M)
    }


def main() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        ttf = tmp / "mdi.ttf"
        scss = tmp / "variables.scss"

        fetch(TTF_URL, ttf)
        fetch(SCSS_URL, scss)

        table = codepoints(scss.read_text())
        missing = [icon for icon in ICONS if icon not in table]
        if missing:
            print(f"not in MDI {MDI_VERSION}: {', '.join(missing)}", file=sys.stderr)
            return 1

        ranges = []
        for index, icon in enumerate(ICONS):
            ranges += ["--range", f"{table[icon]:#x}=>{PUA_BASE + index:#x}"]

        for size in SIZES:
            out = OUT_DIR / f"mdi_font_{size}.c"
            print(f"generating {out.name}")
            subprocess.run(
                [
                    "npx", "--yes", "lv_font_conv@1.5.3",
                    "--font", str(ttf),
                    "--size", str(size),
                    "--bpp", "4",
                    "--format", "lvgl",
                    "--no-compress",
                    "--lv-include", "lvgl.h",
                    "--lv-font-name", f"mdi_font_{size}",
                    "-o", str(out),
                    *ranges,
                ],
                check=True,
            )

    header = OUT_DIR / "mdi_icons.h"
    print(f"generating {header.name}")

    lines = [
        "/*",
        " * Material Design Icons used by the dongle UI, as UTF-8 strings in the",
        f" * private use area. GENERATED by tools/gen_mdi_font.py from MDI {MDI_VERSION}",
        " * — do not edit, and do not add an icon here without adding it to that",
        " * script's ICONS list, or the glyph will be missing from the font.",
        " *",
        " * SPDX-License-Identifier: MIT",
        " */",
        "",
        "#pragma once",
        "",
        "#include <lvgl.h>",
        "",
        "LV_FONT_DECLARE(mdi_font_12);",
        "LV_FONT_DECLARE(mdi_font_10);",
        "",
    ]
    width = max(len(macro_name(icon)) for icon in ICONS)
    for index, icon in enumerate(ICONS):
        utf8 = "".join(f"\\x{byte:02X}" for byte in chr(PUA_BASE + index).encode())
        lines.append(f'#define {macro_name(icon):<{width}} "{utf8}" /* mdi:{icon} */')
    header.write_text("\n".join(lines) + "\n")

    print(f"\n{len(ICONS)} icons, {len(SIZES)} sizes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
