/*
 * Material Design Icons used by the dongle UI, as UTF-8 strings in the
 * private use area. GENERATED by tools/gen_mdi_font.py from MDI 7.4.47
 * — do not edit, and do not add an icon here without adding it to that
 * script's ICONS list, or the glyph will be missing from the font.
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include <lvgl.h>

LV_FONT_DECLARE(mdi_font_12);
LV_FONT_DECLARE(mdi_font_10);

#define MDI_USB                       "\xEE\x80\x80" /* mdi:usb */
#define MDI_BLUETOOTH                 "\xEE\x80\x81" /* mdi:bluetooth */
#define MDI_BLUETOOTH_CONNECT         "\xEE\x80\x82" /* mdi:bluetooth-connect */
#define MDI_BLUETOOTH_OFF             "\xEE\x80\x83" /* mdi:bluetooth-off */
#define MDI_APPLE_KEYBOARD_SHIFT      "\xEE\x80\x84" /* mdi:apple-keyboard-shift */
#define MDI_APPLE_KEYBOARD_CONTROL    "\xEE\x80\x85" /* mdi:apple-keyboard-control */
#define MDI_APPLE_KEYBOARD_OPTION     "\xEE\x80\x86" /* mdi:apple-keyboard-option */
#define MDI_APPLE_KEYBOARD_COMMAND    "\xEE\x80\x87" /* mdi:apple-keyboard-command */
#define MDI_APPLE_KEYBOARD_CAPS       "\xEE\x80\x88" /* mdi:apple-keyboard-caps */
#define MDI_ARROW_UP                  "\xEE\x80\x89" /* mdi:arrow-up */
#define MDI_ARROW_DOWN                "\xEE\x80\x8A" /* mdi:arrow-down */
#define MDI_ARROW_LEFT                "\xEE\x80\x8B" /* mdi:arrow-left */
#define MDI_ARROW_RIGHT               "\xEE\x80\x8C" /* mdi:arrow-right */
#define MDI_ARROW_COLLAPSE_LEFT       "\xEE\x80\x8D" /* mdi:arrow-collapse-left */
#define MDI_ARROW_COLLAPSE_RIGHT      "\xEE\x80\x8E" /* mdi:arrow-collapse-right */
#define MDI_CHEVRON_DOUBLE_UP         "\xEE\x80\x8F" /* mdi:chevron-double-up */
#define MDI_CHEVRON_DOUBLE_DOWN       "\xEE\x80\x90" /* mdi:chevron-double-down */
#define MDI_KEYBOARD_RETURN           "\xEE\x80\x91" /* mdi:keyboard-return */
#define MDI_KEYBOARD_TAB              "\xEE\x80\x92" /* mdi:keyboard-tab */
#define MDI_KEYBOARD_ESC              "\xEE\x80\x93" /* mdi:keyboard-esc */
#define MDI_KEYBOARD_SPACE            "\xEE\x80\x94" /* mdi:keyboard-space */
#define MDI_BACKSPACE_OUTLINE         "\xEE\x80\x95" /* mdi:backspace-outline */
#define MDI_BACKSPACE_REVERSE_OUTLINE "\xEE\x80\x96" /* mdi:backspace-reverse-outline */
#define MDI_VOLUME_OFF                "\xEE\x80\x97" /* mdi:volume-off */
#define MDI_VOLUME_MEDIUM             "\xEE\x80\x98" /* mdi:volume-medium */
#define MDI_VOLUME_HIGH               "\xEE\x80\x99" /* mdi:volume-high */
#define MDI_SKIP_PREVIOUS             "\xEE\x80\x9A" /* mdi:skip-previous */
#define MDI_PLAY_PAUSE                "\xEE\x80\x9B" /* mdi:play-pause */
#define MDI_BRIGHTNESS_5              "\xEE\x80\x9C" /* mdi:brightness-5 */
#define MDI_BRIGHTNESS_7              "\xEE\x80\x9D" /* mdi:brightness-7 */
#define MDI_SKIP_NEXT                 "\xEE\x80\x9E" /* mdi:skip-next */
